AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for index-photos Lambda function
Resources:
  IndexPhotosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: LF1.lambda_handler
      Runtime: python3.9
      CodeUri: s3://photo-album-artifacts/index-photos/  # Placeholder, updated in buildspec
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        IndexPhotosApi:
          Type: Api
          Properties:
            Path: /index-photos
            Method: get