version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -r LF1.zip LF1.py
      - zip -r LF2.zip LF2.py
artifacts:
  files:
    - LF1.zip
    - LF2.zip
