version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - aws cloudformation package --template-file search-photos-template.yaml --output-template-file packaged-search-photos-template.yaml --s3-bucket photo-album-artifacts --s3-prefix search-photos/

artifacts:
  files:
    - packaged-search-photos-template.yaml
  base-directory: search-photos