name: Deploy Lambda Functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [index-photos, search-photos]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.function }}
        pip install -r requirements.txt -t .
        
    - name: Create deployment package
      run: |
        cd ${{ matrix.function }}
        zip -r ../${{ matrix.function }}.zip .
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ matrix.function }} \
          --zip-file fileb://${{ matrix.function }}.zip
